### ISSUE TITLE
Unable to reproduce: missing arm2 package

### ISSUE THREAD

**Issue by hamlinzheng** [osheraz/komodo#2]
Hi Osher, thank you for such an amazing job.
I'm doing some research on automatic digging for wheel loader, thank you very much for open sourcing your work, I'm trying to reproduce it, but meet the following problems:
1. It seems that the **arm2 package** is missing, causing the Gazebo emulator to fail to load files such as `filename="package://arm2/meshes/base_arm.STL"`
2. `objects_on_table.world` seems to be an empty world

This work seems to be a long time ago, sorry if it bothered you, looking forward to your reply.

> Only the robot without the arms and bucket in Gazebo
![2023-02-08_00-57](https://user-images.githubusercontent.com/42463835/217446792-26ffe5dc-dc55-4cc6-8df8-c9625c20d652.jpg)

**Comment by osheraz** [comment]
Hi,

Give this repo a try and see if it works. 
https://github.com/osheraz/random/tree/master/arm2

**Comment by hamlinzheng** [comment]
> Hi,
> 
> Give this repo a try and see if it works. https://github.com/osheraz/random/tree/master/arm2

Thank you very much, it works!
